export const courseData = [
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الإحصاء',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'منه جاد',
    description: 'كورس مادة الاقتصاد',
    grade: 'الصف الثالث الثانوي',
    price: 200,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الفيزياء',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'أحمد علي',
    description: 'كورس مادة الفيزياء',
    grade: 'الصف الثالث الثانوي',
    price: 250,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الكيمياء',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'محمد أحمد',
    description: 'كورس مادة الكيمياء',
    grade: 'الصف الثالث الثانوي',
    price: 220,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الرياضيات',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'سارة عمر',
    description: 'كورس مادة الرياضيات',
    grade: 'الصف الثالث الثانوي',
    price: 180,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'اللغة العربية',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'أحمد سعيد',
    description: 'كورس مادة اللغة العربية',
    grade: 'الصف الثالث الثانوي',
    price: 210,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الجغرافيا',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'ليلى محمود',
    description: 'كورس مادة الجغرافيا',
    grade: 'الصف الثالث الثانوي',
    price: 230,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'التاريخ',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'محمد خالد',
    description: 'كورس مادة التاريخ',
    grade: 'الصف الثالث الثانوي',
    price: 190,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'اللغة الإنجليزية',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'مريم يوسف',
    description: 'كورس مادة اللغة الإنجليزية',
    grade: 'الصف الثالث الثانوي',
    price: 240,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الإحصاء',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'منه جاد',
    description: 'كورس مادة الاقتصاد',
    grade: 'الصف الثالث الثانوي',
    price: 200,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الفيزياء',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'أحمد علي',
    description: 'كورس مادة الفيزياء',
    grade: 'الصف الثالث الثانوي',
    price: 250,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الكيمياء',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'محمد أحمد',
    description: 'كورس مادة الكيمياء',
    grade: 'الصف الثالث الثانوي',
    price: 220,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الرياضيات',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'سارة عمر',
    description: 'كورس مادة الرياضيات',
    grade: 'الصف الثالث الثانوي',
    price: 180,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'اللغة العربية',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'أحمد سعيد',
    description: 'كورس مادة اللغة العربية',
    grade: 'الصف الثالث الثانوي',
    price: 210,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'الجغرافيا',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'ليلى محمود',
    description: 'كورس مادة الجغرافيا',
    grade: 'الصف الثالث الثانوي',
    price: 230,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'التاريخ',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'محمد خالد',
    description: 'كورس مادة التاريخ',
    grade: 'الصف الثالث الثانوي',
    price: 190,
  },
  {
    imageUrl: 'https://via.placeholder.com/325x225',
    subject: 'اللغة الإنجليزية',
    profilePictureUrl: 'https://via.placeholder.com/75',
    teacher: 'مريم يوسف',
    description: 'كورس مادة اللغة الإنجليزية',
    grade: 'الصف الثالث الثانوي',
    price: 240,
  },
];
